---
# tasks file for backupninja
- name: Install Backupninja
  become: "True"
  package:
    name: "{{ item }}"
    use: "apt"
    state: present
  with_items:
    - backupninja

- name: Delete backupninja default files and directories
  become: "True"
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - "/etc/backup.d"
    - "/etc/backupninja.conf"

- name: Install Backupninja sys mode related packages
  become: "True"
  package:
    name: "{{ item }}"
    state: present
    use: "apt"
  with_items:
    - hwinfo
    - debconf-utils
    - flashrom
  when: ninja.include_sys_checks

- name: Install Backupninja rdiff mode related packages
  become: "True"
  package:
    name: "{{ item }}"
    state: present
    use: "apt"
  with_items:
    - rdiff-backup
  when: ninja.backup_method == 'rdiff'

- name: Create required directories
  become: "True"
  file:
    name: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0700
  with_items:
    - "/etc/backupninja/"
    - "/etc/backupninja/{{ ninja.backup_name }}"
    - "/etc/backupninja/{{ ninja.backup_name }}/backup.d"
    - "/var/log/backupninja/"
    - "{{ ninja.backup_dir }}"
    - "{{ ninja.temp_backup_dir }}"

- name: Deploy config template
  become: "True"
  template:
    src: backupninja.conf.j2
    dest: "/etc/backupninja/{{ ninja.backup_name }}/backupninja.conf"
    mode: '0600'
    owner: root
    group: root

- name: Deploy system info backup template
  become: "True"
  template:
    src: sys.j2
    dest: "/etc/backupninja/{{ ninja.backup_name }}/backup.d/10.sys"
    mode: '0600'
    owner: root
    group: root
  when: ninja.include_sys_checks

- name: Deploy directories backup template
  become: "True"
  template:
    src: rdiff.j2
    dest: "/etc/backupninja/{{ ninja.backup_name }}/backup.d/80.rdiff"
    mode: '0600'
    owner: root
    group: root
  when: ninja.backup_method == 'rdiff'

- name: Include extra backup steps
  become: "True"
  copy:
    src: "{{ item }}"
    dest: "/etc/backupninja/{{ ninja.backup_name }}/backup.d/"
    mode: '0700'
    owner: root
    group: root
  with_items: "{{ ninja.include_backup_steps }}"

- name: Set up the system cron
  become: "True"
  cron:
    name: "Execute {{ ninja.backup_name }} backupninja job"
    cron_file: /etc/cron.d/backupninja
    special_time: hourly
    user: root
    job: "/usr/sbin/backupninja -f /etc/backupninja/{{ ninja.backup_name }}/backupninja.conf"

- name: Set up the cron hourly
  become: "True"
  cron:
    name: "Execute backupninja hourly"
    special_time: hourly
    job: "/usr/sbin/backupninja -f /etc/backupninja/{{ ninja.backup_name }}/backupninja.conf -n"
  when: ninja.execute_hourly
