---
- name: Converge
  hosts: all
  vars:
    ninja:
      email_to_report: "lyz@gentooza.me"
      backup_retention_period: "60D"
      backup_method: 'rdiff'
      include:
        - "/var/spool/cron/crontabs"
        - "/var/backups"
        - "/etc"
        - "/root"
        - "/home"
        - "/usr/local/bin"
        - "/usr/local/sbin"
        - "/var/lib/dpkg/status"
        - "/var/lib/dpkg/status-old"
      exclude:
        - "/tmp"
      temp_backup_dir: "/var/backups/"
      execute_hourly: true
      backup_dir: "/backups"
      when: "everyday at 13"
      include_sys_checks: false
      backup_name: main
      include_backup_steps: []
  roles:
    - role: backupninja

- name: '[Post action] Execute backupninja'
  hosts: all
  tasks:
    - name: 'Execute backupninja'
      command: 'backupninja -f /etc/backupninja/main/backupninja.conf -n'
      changed_when: false
